language: php
dist: trusty
sudo: required

cache:
  directories:
    - $HOME/.composer/cache/files

services:
  - docker

php:
  - 7.4

env:
  global:
    - DRUPAL_BASE_URL="http://127.0.0.1:8080"

install:
  - composer --verbose install  
