language: php
dist: xenial

services:
  - docker

php:
  - 7.4

script:
- echo "skipping tests"

env:
  global:
    - XDEBUG_MODE=coverage

before_install:
  - echo -e "Host codeserver.dev.8b106de4-5eae-4105-9881-834d33a72e16.drush.in\nStrictHostKeyChecking no\n" >> ~/.ssh/config #put in travis config.

install:
  # - composer --verbose install
  - .travis/deploy.sh
